USER_PATH = "/Users/preetamepari/Downloads/dinerate_users.csv"
REVIEWS_PATH = "/Users/preetamepari/Downloads/dinerate_reviews.csv"
RESTAURANTS_PATH = "/Users/preetamepari/Downloads/dinerate_restaurants-2.csv"
OUTPUT_PATH = "/Users/preetamepari/Downloads/dinerate_joined_output"
JDBC_DRIVER_PATH = "/Users/preetamepari/jdbc_drivers/postgresql-42.7.1.jar"
POSTGRES_URL = "jdbc:postgresql://yamanote.proxy.rlwy.net:22726/railway"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "oLRJtHqohvlxvPZjPilWmnqXkSlNZFQk"
